// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Penca_uy2026.Data;

#nullable disable

namespace Penca_uy2026.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260514031328_ManualFixUrl")]
    partial class ManualFixUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Penca_uy2026.Models.Deporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Deportes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Fútbol"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Básquetbol"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Tenis"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Vóleibol"
                        });
                });

            modelBuilder.Entity("Penca_uy2026.Models.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PencaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PencaId");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("Penca_uy2026.Models.Invitacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SitioId")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SitioId");

                    b.ToTable("Invitaciones");
                });

            modelBuilder.Entity("Penca_uy2026.Models.MensajeChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<int>("ParticipacionId")
                        .HasColumnType("int");

                    b.Property<int>("SitioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParticipacionId");

                    b.ToTable("MensajesChat");
                });

            modelBuilder.Entity("Penca_uy2026.Models.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FueLeida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SitioId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioSitioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioSitioId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("Penca_uy2026.Models.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdTransaccionExterna")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ParticipacionId")
                        .HasColumnType("int");

                    b.Property<int>("SitioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParticipacionId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("Penca_uy2026.Models.Participacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstaPagado")
                        .HasColumnType("bit");

                    b.Property<int>("PencaInstanciaId")
                        .HasColumnType("int");

                    b.Property<int>("PuntajeTotal")
                        .HasColumnType("int");

                    b.Property<int>("SitioId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioSitioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PencaInstanciaId");

                    b.HasIndex("UsuarioSitioId");

                    b.ToTable("Participaciones");
                });

            modelBuilder.Entity("Penca_uy2026.Models.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Fase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GolesLocal")
                        .HasColumnType("int");

                    b.Property<int?>("GolesVisitante")
                        .HasColumnType("int");

                    b.Property<bool>("Jugado")
                        .HasColumnType("bit");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PencaId")
                        .HasColumnType("int");

                    b.Property<string>("Visitante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PencaId");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("Penca_uy2026.Models.Penca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadEquipos")
                        .HasColumnType("int");

                    b.Property<int>("DeporteId")
                        .HasColumnType("int");

                    b.Property<bool>("Finalizada")
                        .HasColumnType("bit");

                    b.Property<int>("Modo")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeporteId");

                    b.ToTable("Pencas");
                });

            modelBuilder.Entity("Penca_uy2026.Models.PencaInstancia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PencaId")
                        .HasColumnType("int");

                    b.Property<decimal>("PorcentajeComision")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SitioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PencaId");

                    b.HasIndex("SitioId");

                    b.ToTable("PencaInstancias");
                });

            modelBuilder.Entity("Penca_uy2026.Models.PlataformaAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlataformaAdmins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@tupenca.uy",
                            PasswordHash = "$2a$11$XJYwFyQsoePf2PAkwRgXD.Ske1iMlVsHqodB8ikf3CWwXwI2pCIza"
                        });
                });

            modelBuilder.Entity("Penca_uy2026.Models.Prediccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GolesEquipoLocal")
                        .HasColumnType("int");

                    b.Property<int>("GolesEquipoVisitante")
                        .HasColumnType("int");

                    b.Property<int>("ParticipacionId")
                        .HasColumnType("int");

                    b.Property<int>("PartidoId")
                        .HasColumnType("int");

                    b.Property<int>("PuntosObtenidos")
                        .HasColumnType("int");

                    b.Property<int>("SitioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParticipacionId");

                    b.HasIndex("PartidoId");

                    b.ToTable("Predicciones");
                });

            modelBuilder.Entity("Penca_uy2026.Models.Sitio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ColorPrincipal")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TipoRegistro")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Sitios");
                });

            modelBuilder.Entity("Penca_uy2026.Models.SolicitudIngreso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SitioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SitioId");

                    b.ToTable("SolicitudesIngreso");
                });

            modelBuilder.Entity("Penca_uy2026.Models.UsuarioSitio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Auth0Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FcmToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<int>("SitioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SitioId");

                    b.ToTable("UsuariosSitio");
                });

            modelBuilder.Entity("Penca_uy2026.Models.Equipo", b =>
                {
                    b.HasOne("Penca_uy2026.Models.Penca", null)
                        .WithMany("Equipos")
                        .HasForeignKey("PencaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Penca_uy2026.Models.Invitacion", b =>
                {
                    b.HasOne("Penca_uy2026.Models.Sitio", "Sitio")
                        .WithMany("Invitaciones")
                        .HasForeignKey("SitioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sitio");
                });

            modelBuilder.Entity("Penca_uy2026.Models.MensajeChat", b =>
                {
                    b.HasOne("Penca_uy2026.Models.Participacion", "Participacion")
                        .WithMany("MensajesChat")
                        .HasForeignKey("ParticipacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Participacion");
                });

            modelBuilder.Entity("Penca_uy2026.Models.Notificacion", b =>
                {
                    b.HasOne("Penca_uy2026.Models.UsuarioSitio", "UsuarioSitio")
                        .WithMany("Notificaciones")
                        .HasForeignKey("UsuarioSitioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioSitio");
                });

            modelBuilder.Entity("Penca_uy2026.Models.Pago", b =>
                {
                    b.HasOne("Penca_uy2026.Models.Participacion", "Participacion")
                        .WithMany("Pagos")
                        .HasForeignKey("ParticipacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Participacion");
                });

            modelBuilder.Entity("Penca_uy2026.Models.Participacion", b =>
                {
                    b.HasOne("Penca_uy2026.Models.PencaInstancia", "PencaInstancia")
                        .WithMany("Participaciones")
                        .HasForeignKey("PencaInstanciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Penca_uy2026.Models.UsuarioSitio", "UsuarioSitio")
                        .WithMany("Participaciones")
                        .HasForeignKey("UsuarioSitioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PencaInstancia");

                    b.Navigation("UsuarioSitio");
                });

            modelBuilder.Entity("Penca_uy2026.Models.Partido", b =>
                {
                    b.HasOne("Penca_uy2026.Models.Penca", null)
                        .WithMany("Partidos")
                        .HasForeignKey("PencaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Penca_uy2026.Models.Penca", b =>
                {
                    b.HasOne("Penca_uy2026.Models.Deporte", "Deporte")
                        .WithMany()
                        .HasForeignKey("DeporteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Deporte");
                });

            modelBuilder.Entity("Penca_uy2026.Models.PencaInstancia", b =>
                {
                    b.HasOne("Penca_uy2026.Models.Penca", "Penca")
                        .WithMany("Instancias")
                        .HasForeignKey("PencaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Penca_uy2026.Models.Sitio", "Sitio")
                        .WithMany("PencaInstancias")
                        .HasForeignKey("SitioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Penca");

                    b.Navigation("Sitio");
                });

            modelBuilder.Entity("Penca_uy2026.Models.Prediccion", b =>
                {
                    b.HasOne("Penca_uy2026.Models.Participacion", "Participacion")
                        .WithMany("Predicciones")
                        .HasForeignKey("ParticipacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Penca_uy2026.Models.Partido", "Partido")
                        .WithMany()
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Participacion");

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("Penca_uy2026.Models.SolicitudIngreso", b =>
                {
                    b.HasOne("Penca_uy2026.Models.Sitio", "Sitio")
                        .WithMany("SolicitudesIngreso")
                        .HasForeignKey("SitioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sitio");
                });

            modelBuilder.Entity("Penca_uy2026.Models.UsuarioSitio", b =>
                {
                    b.HasOne("Penca_uy2026.Models.Sitio", "Sitio")
                        .WithMany("Usuarios")
                        .HasForeignKey("SitioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sitio");
                });

            modelBuilder.Entity("Penca_uy2026.Models.Participacion", b =>
                {
                    b.Navigation("MensajesChat");

                    b.Navigation("Pagos");

                    b.Navigation("Predicciones");
                });

            modelBuilder.Entity("Penca_uy2026.Models.Penca", b =>
                {
                    b.Navigation("Equipos");

                    b.Navigation("Instancias");

                    b.Navigation("Partidos");
                });

            modelBuilder.Entity("Penca_uy2026.Models.PencaInstancia", b =>
                {
                    b.Navigation("Participaciones");
                });

            modelBuilder.Entity("Penca_uy2026.Models.Sitio", b =>
                {
                    b.Navigation("Invitaciones");

                    b.Navigation("PencaInstancias");

                    b.Navigation("SolicitudesIngreso");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Penca_uy2026.Models.UsuarioSitio", b =>
                {
                    b.Navigation("Notificaciones");

                    b.Navigation("Participaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
