// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Penca_uy2026.Data;

#nullable disable

namespace Penca_uy2026.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260426223321_AgregarTablasPencasYDeportes")]
    partial class AgregarTablasPencasYDeportes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Penca_uy2026.Models.Deporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Deportes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Fútbol"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Básquetbol"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Tenis"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Vóleibol"
                        });
                });

            modelBuilder.Entity("Penca_uy2026.Models.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PencaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PencaId");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("Penca_uy2026.Models.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Fase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GolesLocal")
                        .HasColumnType("integer");

                    b.Property<int?>("GolesVisitante")
                        .HasColumnType("integer");

                    b.Property<bool>("Jugado")
                        .HasColumnType("boolean");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PencaId")
                        .HasColumnType("integer");

                    b.Property<string>("Visitante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PencaId");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("Penca_uy2026.Models.Penca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadEquipos")
                        .HasColumnType("integer");

                    b.Property<int>("DeporteId")
                        .HasColumnType("integer");

                    b.Property<bool>("Finalizada")
                        .HasColumnType("boolean");

                    b.Property<int>("Modo")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeporteId");

                    b.ToTable("Pencas");
                });

            modelBuilder.Entity("Penca_uy2026.Models.PlataformaAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PlataformaAdmins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@tupenca.uy",
                            PasswordHash = "$2a$11$kMhqSS6jw1fkuJrGnb3pxe6FaYXFoPpv5UU0uekkWgrr/HvifCS.q"
                        });
                });

            modelBuilder.Entity("Penca_uy2026.Models.Equipo", b =>
                {
                    b.HasOne("Penca_uy2026.Models.Penca", null)
                        .WithMany("Equipos")
                        .HasForeignKey("PencaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Penca_uy2026.Models.Partido", b =>
                {
                    b.HasOne("Penca_uy2026.Models.Penca", null)
                        .WithMany("Partidos")
                        .HasForeignKey("PencaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Penca_uy2026.Models.Penca", b =>
                {
                    b.HasOne("Penca_uy2026.Models.Deporte", "Deporte")
                        .WithMany()
                        .HasForeignKey("DeporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deporte");
                });

            modelBuilder.Entity("Penca_uy2026.Models.Penca", b =>
                {
                    b.Navigation("Equipos");

                    b.Navigation("Partidos");
                });
#pragma warning restore 612, 618
        }
    }
}
