// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Penca_uy2026.Data;

#nullable disable

namespace Penca_uy2026.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260426222524_SistemaPencasCompleto")]
    partial class SistemaPencasCompleto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Penca_uy2026.Models.PlataformaAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PlataformaAdmins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@tupenca.uy",
                            PasswordHash = "$2a$11$O98kmr4BifIo.yO3kIguQeg3Z3twpuy7qG39RNbXJv4Qc3KyDcJhS"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
