// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Penca_uy2026.Data;

#nullable disable

namespace Penca_uy2026.Data.Migrations
{
    [DbContext(typeof(PencaDbContext))]
    [Migration("20260429023056_AddPencasEvTeams")]
    partial class AddPencasEvTeams
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Penca_uy2026.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PencaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("PencaId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Penca_uy2026.Models.Participation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<int>("PencaInstanceId")
                        .HasColumnType("int");

                    b.Property<int>("SiteUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PencaInstanceId");

                    b.HasIndex("SiteUserId");

                    b.ToTable("Participations");
                });

            modelBuilder.Entity("Penca_uy2026.Models.Penca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Pencas");
                });

            modelBuilder.Entity("Penca_uy2026.Models.PencaInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PencaId")
                        .HasColumnType("int");

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PencaId");

                    b.HasIndex("SiteId");

                    b.ToTable("PencaInstances");
                });

            modelBuilder.Entity("Penca_uy2026.Models.Prediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayTeamScore")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeamScore")
                        .HasColumnType("int");

                    b.Property<int>("ParticipationId")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("ParticipationId");

                    b.ToTable("Predictions");
                });

            modelBuilder.Entity("Penca_uy2026.Models.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("Penca_uy2026.Models.SiteUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("SiteUsers");
                });

            modelBuilder.Entity("Penca_uy2026.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Penca_uy2026.Models.Event", b =>
                {
                    b.HasOne("Penca_uy2026.Models.Team", "AwayTeam")
                        .WithMany("AwayEvents")
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Penca_uy2026.Models.Team", "HomeTeam")
                        .WithMany("HomeEvents")
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Penca_uy2026.Models.Penca", "Penca")
                        .WithMany("Events")
                        .HasForeignKey("PencaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("Penca");
                });

            modelBuilder.Entity("Penca_uy2026.Models.Participation", b =>
                {
                    b.HasOne("Penca_uy2026.Models.PencaInstance", "PencaInstance")
                        .WithMany("Participations")
                        .HasForeignKey("PencaInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Penca_uy2026.Models.SiteUser", "SiteUser")
                        .WithMany("Participations")
                        .HasForeignKey("SiteUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PencaInstance");

                    b.Navigation("SiteUser");
                });

            modelBuilder.Entity("Penca_uy2026.Models.PencaInstance", b =>
                {
                    b.HasOne("Penca_uy2026.Models.Penca", "Penca")
                        .WithMany("Instances")
                        .HasForeignKey("PencaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Penca_uy2026.Models.Site", "Site")
                        .WithMany("PencaInstances")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Penca");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Penca_uy2026.Models.Prediction", b =>
                {
                    b.HasOne("Penca_uy2026.Models.Event", "Event")
                        .WithMany("Predictions")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Penca_uy2026.Models.Participation", "Participation")
                        .WithMany("Predictions")
                        .HasForeignKey("ParticipationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Participation");
                });

            modelBuilder.Entity("Penca_uy2026.Models.SiteUser", b =>
                {
                    b.HasOne("Penca_uy2026.Models.Site", "Site")
                        .WithMany("SiteUsers")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Penca_uy2026.Models.Event", b =>
                {
                    b.Navigation("Predictions");
                });

            modelBuilder.Entity("Penca_uy2026.Models.Participation", b =>
                {
                    b.Navigation("Predictions");
                });

            modelBuilder.Entity("Penca_uy2026.Models.Penca", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Instances");
                });

            modelBuilder.Entity("Penca_uy2026.Models.PencaInstance", b =>
                {
                    b.Navigation("Participations");
                });

            modelBuilder.Entity("Penca_uy2026.Models.Site", b =>
                {
                    b.Navigation("PencaInstances");

                    b.Navigation("SiteUsers");
                });

            modelBuilder.Entity("Penca_uy2026.Models.SiteUser", b =>
                {
                    b.Navigation("Participations");
                });

            modelBuilder.Entity("Penca_uy2026.Models.Team", b =>
                {
                    b.Navigation("AwayEvents");

                    b.Navigation("HomeEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
